version: '3.9'

services:
  app:
    build:
      context: .
      args:
        BASE_PATH: ${BASE_PATH:-}
    restart: on-failure
    env_file: .env
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - '${PORT:-3000}:3000'
